config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'users/registrations'}
  resources :friends
  root 'home#index'
  get 'home/about'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    validates :first_name, presence: true, length: { minimum: 3, maximum: 50 }
  	validates :last_name, presence: true, length: { minimum: 3, maximum: 50 }
	validates :image, presence: true

	has_one_attached :image 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about    
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:image])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-4 text-center">
      <% if friend.image.attached? %>
        <%= image_tag(friend.image, style: 'height: 400px;', class: 'img-thumbnail', id: "preview_id") %>
      <% else %>  
        <%= image_tag("https://conferenceoeh.com/wp-content/uploads/profile-pic-dummy.png", style: 'height: 400px;', class: 'img-thumbnail', id: "preview_id") %>
      <% end %>
    </div>
  <div class="col-sm-8">  
  <div class="form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Email Address" %>
  </div>

  <div class="form-group">
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone Number" %>
  </div>
  <div class="form-group">
    <%= form.file_field :image, class: "form-control", placeholder: "Photo", id: "image_upload_id", onchange: "previewImage(event);" %>
  </div>
  <br/>
  
  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
  </div>
  </div>  
<% end %>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id friend %>">
  <td style="width: 80px;">
    <% if friend.image.attached? %>
      <%= image_tag(friend.image, style: 'width: 100%', class: 'rounded-circle') %>
    <% else %>
      <%= image_tag("https://conferenceoeh.com/wp-content/uploads/profile-pic-dummy.png", style: 'width: 100%', class: 'rounded-circle') %>
    <% end %>
  </td>
  <td class="align-middle">
    <%= link_to friend.first_name + ' ' + friend.last_name , friend %>
  </td>
  <td class="align-middle">
    <%= friend.email %>
  </td>
  <td class="align-middle">
    <%= friend.phone %>
  </td>
  <td class="align-middle">
    <%= button_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
  </td>
</tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<table class="table table-striped table-bordered table-hover">
   <thead class="table-dark">
    <th class="text-center">###</th>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th class="text-center">Action</th>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <%= render friend %>
    <% end %>
  </tbody>
</table>

<%= link_to "New friend", new_friend_path, class: "btn btn-secondary" %>
<br/>
<br/>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<div class="p-5 mb-4 bg-light rounded-12 bg-light border">
    <div class="container-fluid py-5 text-center">
      <div class="row">
      <div class="col" style="width: 200px; height: auto;">
      <!-- <div style="width: 200px; height: auto;"> -->
        <%# image_tag(@friend.image, style: 'width: 40%') %>
        <% if @friend.image.attached? %>
      <%= image_tag(@friend.image, style: 'width: 40%', class: 'img-thumbnail') %>
    <% else %>
      <%= image_tag("https://conferenceoeh.com/wp-content/uploads/profile-pic-dummy.png", style: 'width: 40%', class: 'img-thumbnail') %>
    <% end %>
      <!-- </div> -->
      <!-- <div style="width: 200px; height: auto;"> -->
      </div>
      </div> 
      <h1 class="display-5 fw-bold"><%= @friend.first_name %> <%= @friend.last_name %></h1>
      <p class="fs-5">
        <%= @friend.email %> |  <%= @friend.phone %>
      </p>
      <br/>
      <div class="row">
      <div class="col">
        <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-dark form-control" %> 
      </div>
      <div class="col">    
        <%= link_to "Back", friends_path, class: "btn btn-secondary form-control" %>
      </div>
      <div class="col"> 
        <%= button_to "Delete", @friend, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger form-control" %>
      </div>
    </div> 
    </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <%= link_to 'Friends App', root_path, class:"navbar-brand" %>
  <!-- <a class="navbar-brand" href="#">Friends App</a> -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Friends', friends_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Add a new friend', new_friend_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
      	<%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
      	<%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
      </li>      
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        <!-- <a class="nav-link" href="#">Link</a> -->
      </li>
      
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <% if user_signed_in? %>
      <% if current_user.image.attached? %>
        <%= image_tag(current_user.image, style: "height: 50px; width: 50px;", class: 'rounded-circle') %>
        &nbsp;&nbsp;
      <% end %>
      <span class="navbar-text">
        Logged in as, <strong><%= current_user.email %> </strong>
      </span>
      &nbsp;&nbsp;
        <%= button_to 'Sign Out', destroy_user_session_path, data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-outline-danger btn-sm my-2 my-sm-0" %>
      <% end %>
      <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<br/><br/><br/>
<br/><br/><br/>
<h1>About Us...</h1>
<br/>
<p>
dsnfksdn ksakdnksni waindsdjkasdnjksadjksndnsadaijdnd
dkawndkajdnandknakdnand jhbdshdjshu aiwi iwnnsjkdllsl
jksjfkjkfk kakawiqpa ksfksdkfdsfs lsk  klask to klsdl
dsnfksdn ksakdnksni waindsdjkasdnjksadjksndnsadaijdnd
dkawndkajdnandknakdnand jhbdshdjshu aiwi iwnnsjkdllsl
jksjfkjkfk kakawiqpa ksfksdkfdsfs lsk  klask to klsdl
dsnfksdn ksakdnksni waindsdjkasdnjksadjksndnsadaijdnd
dkawndkajdnandknakdnand jhbdshdjshu aiwi iwnnsjkdllsl
jksjfkjkfk kakawiqpa ksfksdkfdsfs lsk  klask to klsdl
</p>

app/views/home/index.html.erb
<br/><br/><br/>
<br/><br/><br/>
<h1>Welcome friend</h1>
<br/>
<br/>
<p>
Find me in 
<br/>
dsnfksdn ksakdnksni waindsdjkasdnjksadjksndnsadaijdnd
dkawndkajdnandknakdnand jhbdshdjshu aiwi iwnnsjkdllsl
jksjfkjkfk kakawiqpa ksfksdkfdsfs lsk  klask to klsdl
dsnfksdn ksakdnksni waindsdjkasdnjksadjksndnsadaijdnd
dkawndkajdnandknakdnand jhbdshdjshu aiwi iwnnsjkdllsl
jksjfkjkfk kakawiqpa ksfksdkfdsfs lsk  klask to klsdl
dsnfksdn ksakdnksni waindsdjkasdnjksadjksndnsadaijdnd
dkawndkajdnandknakdnand jhbdshdjshu aiwi iwnnsjkdllsl
jksjfkjkfk kakawiqpa ksfksdkfdsfs lsk  klask to klsdl
</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->


    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
   <%= render 'home/header' %>
  <div class="container">
     
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>       
      <%= yield %>
    </div>
  <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script> -->

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <%# <script src="assets/application.js"></script> %>
    <script>
      const previewImage = (event) => {
        
        const imageFiles = event.target.files;
        
        const imageFilesLength = imageFiles.length;
        
        if (imageFilesLength > 0) {
            
            const imageSrc = URL.createObjectURL(imageFiles[0]);
            
            const imagePreviewElement = document.querySelector("#preview_id");
            
            imagePreviewElement.src = imageSrc;
            
            // imagePreviewElement.style.display = "block";
        }
      };
    </script>
  </body>
</html>